In [3]:
### NumPy
# 고성능 수치 계산을 위해서 제작된 파이썬 라이브러리
# 머신러닝 또는 딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산으로 볼 수 있음. 
# 또는 대량의 데이터를 다룰 때 빠른 계산 능력이 요구되어 사용되는 라이브러리

# 생성된 NumPy 확인 - NumPy의 핵심객체(Ndarray) 
import numpy as np

temp = np.array([1,2,3])

print(temp)

## 튜토리얼 : https://numpy.org/doc/stable/user/quickstart.html

[1 2 3]


In [14]:
# NumPy 기본 문법

# - list
data1 = [1,2,3]
data1

data2 = [1,1,2,2,3,4]
data2

# np.array으로 배열 변환
my_array1 = np.array(data1)
print(my_array1)
print(my_array1.shape)

my_array2 = np.array(data2)
print(my_array2)
print(my_array2.shape)

# shape는 크기를 확인하는 함수

## 리스트 선언 없이 바로 np.array로 사용
my_array3 = np.array([3,4,5,12])
print(my_array3.dtype)

## Data Types 참조 : https://numpy.org/devdocs/user/basics.types.html

[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
int32


In [16]:
### 2차 배열
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
my_array4
my_array4.shape # (4,3)의 형태

(4, 3)

In [22]:
### 3차 배열
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
my_array5
my_array5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
### NumPy 배열 생성 및 둘러보기
# Arange : 기본 함수 중에 Range함수와 조금 유사하며, 더욱 쉽게 배열을 만들게 함. 
arrange_array = np.arange(5)
print(arrange_array)

arrange_array = np.arange(1, 9, 3) # 시작값, 종료값, 증감값 순으로 설정
print(arrange_array)
arrange_array.dtype


[0 1 2 3 4]
[1 4 7]


dtype('int32')

In [39]:
### Zeros, Ones 
# 할당하는 사이즈 배열에 0 이나 1을 더욱 쉽게 입력하는 함수
zeros_arr = np.zeros((3,2))
print(zeros_arr)
print("Data Type is : ",zeros_arr.dtype)
print("Data Shape is : ", zeros_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is :  float64
Data Shape is :  (3, 2)


In [40]:
ones_arr = np.ones((3,4),dtype="int32")
print(ones_arr)
print("Data Type is : ",ones_arr.dtype)
print("Data Shape is : ", ones_arr.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type is :  int32
Data Shape is :  (3, 4)


In [47]:
## Reshape
after_reshape = ones_arr.reshape(6,2)
print(after_reshape)
print("Data Shape is : ", after_reshape.shape)

## 항상 변경이 가능하지는 않다. 조건은 Size가 동일해야 한다.
# ones_arr를 다른 사이즈 변경해보세요. 3가지정도
ones_arr2 = ones_arr.reshape(2,3,2)
print(ones_arr2)
ones_arr3 = ones_arr.reshape(3,2,2)
print(ones_arr3)
ones_arr4 = ones_arr.reshape(2,2,3)
print(ones_arr4)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is :  (6, 2)
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [52]:
### reshape()에서 -1의 의미는 ? 차원을 자동으로 계산한다는 의미
after_reshape4 = ones_arr.reshape(3,-1)
print(after_reshape4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [55]:
### NumPy 인덱싱과 슬라이싱
my_array = np.arange(0, 4)
print(my_array)

print("my_array의 1번째 요소, 즉 0번인 것은 : ",my_array[0])
print("my_array[0:3] : ", my_array[0:3])
print("my_array[0:] : ", my_array[0:])
print("my_array[0:2] : ", my_array[0:2])
print("my_array[:] : ", my_array[:])
print("my_array[0:-1] : ", my_array[0:-1])



[0 1 2 3]
my_array의 1번째 요소, 즉 0번인 것은 :  0
my_array[0:3] :  [0 1 2]
my_array[0:] :  [0 1 2 3]
my_array[0:2] :  [0 1]
my_array[:] :  [0 1 2 3]
my_array[0:-1] :  [0 1 2]


In [68]:
my_array2 = np.array(
    [
    [2,4,6,8,10,12,14,16,18],
    [3,6,9,12,15,18,21,24,27],
    [4,8,12,16,20,24,28,32,36],
    [5,10,15,20,25,30,35,40,45],
    ]
)

print(my_array2)
print(my_array2.shape)
print(my_array2[0:2, 0:2])
print(my_array2[1:3, :])


[[ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]]
(4, 9)
[[2 4]
 [3 6]]
[[ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]]


In [73]:
### NumPy정렬 : sort(), argsort()

## np.sort()
height_arr = np.array([174, 165, 182, 180, 168])
sorted_height_arr = np.sort(height_arr)
print("Height Matrix : ",height_arr)
print("np.sort() Matrix : ", sorted_height_arr)

# 내림차순 정렬
desc_sorted_height_arr = np.sort(height_arr)[::-1]
print("np.sort()[::-] : ", desc_sorted_height_arr)


Height Matrix :  [174 165 182 180 168]
np.sort() Matrix :  [165 168 174 180 182]
np.sort()[::-] :  [182 180 174 168 165]


In [78]:
### argsort()
# numpy.argsort() 함수는 지정된 축을 따라 데이터 인덱스의 배열을 반환하도록 지정된 종류의 정렬을 사용해
# 입력 배열에서 간접 정렬을 수행함.

fives = np.array([10,5,15,20])
fives_order = fives.argsort()

print("original data : ", fives)
print("argsort() : ", fives_order)      # 인덱싱 값 반환
print("Ascending : ", fives[fives_order])

# NumPyTutorials : https://numpy.org/learn/
# NumPy Broadcasting : https://numpy.org/doc/stable/user/basics.broadcasting.html
# 숙제... 같은 크기의 두 배열에 대한 연산과 서로 크기가 다른 두 배열의 연산을 공부하세요.

original data :  [10  5 15 20]
argsort() :  [1 0 2 3]
Ascending :  [20 15 10  5]
